# Generated by Django 4.2.5 on 2023-10-01 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_band_active_band_biography_band_genre_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notice',
            new_name='Listing',
        ),
    ]
